/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.*;
import Modelo.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Fabrizio
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public ventanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Sistema de Ventas y Reabastecimiento para Minimarkets");
        setSize(600, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
        initComponentes();
    }

    //Variables globales
    private inventario inventario = new inventario();
    private colaReabastecimiento cola = new colaReabastecimiento();

    private JTextField txtCodigo, txtNombre, txtCantidad, txtMinimo, txtVenta;
    private JTextArea areaCola;

    private void initComponentes() {
        JLabel lblCod = new JLabel("Código:");
        JLabel lblNom = new JLabel("Nombre:");
        JLabel lblCant = new JLabel("Cantidad:");
        JLabel lblMin = new JLabel("Mínimo:");
        JLabel lblVenta = new JLabel("Código a vender:");

        txtCodigo = new JTextField();
        txtNombre = new JTextField();
        txtCantidad = new JTextField();
        txtMinimo = new JTextField();
        txtVenta = new JTextField();

        JButton btnAgregar = new JButton("Agregar Producto");
        JButton btnVender = new JButton("Registrar Venta");
        JButton btnVerCola = new JButton("Ver Cola");

        areaCola = new JTextArea();
        areaCola.setEditable(false);
        JScrollPane scroll = new JScrollPane(areaCola);

        // Posiciones
        lblCod.setBounds(20, 20, 100, 20);
        txtCodigo.setBounds(120, 20, 150, 20);
        lblNom.setBounds(20, 50, 100, 20);
        txtNombre.setBounds(120, 50, 150, 20);
        lblCant.setBounds(20, 80, 100, 20);
        txtCantidad.setBounds(120, 80, 150, 20);
        lblMin.setBounds(20, 110, 100, 20);
        txtMinimo.setBounds(120, 110, 150, 20);
        btnAgregar.setBounds(300, 50, 200, 30);

        lblVenta.setBounds(20, 160, 150, 20);
        txtVenta.setBounds(160, 160, 150, 20);
        btnVender.setBounds(320, 160, 150, 30);
        btnVerCola.setBounds(200, 210, 180, 30);
        scroll.setBounds(20, 250, 500, 100);

        add(lblCod);
        add(txtCodigo);
        add(lblNom);
        add(txtNombre);
        add(lblCant);
        add(txtCantidad);
        add(lblMin);
        add(txtMinimo);
        add(btnAgregar);
        add(lblVenta);
        add(txtVenta);
        add(btnVender);
        add(btnVerCola);
        add(scroll);

        // Acciones
        btnAgregar.addActionListener(e -> {
            try {
                String cod = txtCodigo.getText();
                String nom = txtNombre.getText();
                int cant = Integer.parseInt(txtCantidad.getText());
                int min = Integer.parseInt(txtMinimo.getText());
                producto p = new producto(cod, nom, cant, min);
                inventario.agregarProducto(p);
                JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");
                txtCodigo.setText("");
                txtNombre.setText("");
                txtCantidad.setText("");
                txtMinimo.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error en los datos ingresados.");
            }
        });

        btnVender.addActionListener(e -> {
            String cod = txtVenta.getText();
            producto p = inventario.buscar(cod);
            if (p != null) {
                p.vender(1);
                if (p.necesitaReabastecimiento()) {
                    cola.insertar(p);
                }
                JOptionPane.showMessageDialog(this, "Venta registrada.");
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            }
        });

        btnVerCola.addActionListener(e -> {
            if (cola.estaVacia()) {
                areaCola.setText("No hay productos en la cola de reabastecimiento.");
            } else {
                areaCola.setText("Cola de Reabastecimiento:\n" + cola.mostrarCola());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
